absorb-key: "r"
soul-circle:
  十年魂环:
    url: "十年魂环.png"
    #图片地址
    view-time: 10
    #显示时间
    absorb-time: 5
    #吸收时间
    absorb-sure-level: 10
    #吸收等级
    probability: 100.0
    #成功几率
    success-string-action:
      - "吸收成功"
    count-down-task-string-action:
      - "吸收倒计时 %time%"
    fail-string-action:
      - "吸收失败"
    world-texture: "test"
    animation:
      - 'test-rotate'
      - 'test-translate'
world-texture:
  #贴图设置
  "test":
    glow: true
    height: 3.0
    width: 3.0
    translate-x: 0.0
    translate-y: 3.5
    translate-z: 0.0
    rotate-x: 90
    rotate-y: 0
    rotate-z: 0
    follow-entity-direction: true
animations:
  #旋转动画设置
  "test-rotate":
    type: "rotate"
    direction: "z"
    #旋转方向
    angle: 360
    #角度
    duration: 3000
    #持续时间
    cycle-count: -1
    #循环次数，-1为永久循环
    fixed: false
    #是否到达位置停止动画
  "test-translate":
    type: "translate"
    direction: "z"
    #方向
    distance: 2.5
    #移动距离
    cycle-count: 1
    #循环次数，-1为永久循环
    duration: 3000
    #持续时间
    fixed: true
    #是否到达位置后停止动画